spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springboot_learning?characterEncoding=utf-8&useSSL=false

server:
  context-path: /userCentre